env:
  browser: true
  es2021: true
plugins:
  - solid
extends:
  - eslint:recommended
  - plugin:solid/recommended
  - standard-with-typescript
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project:
    - tsconfig.json
rules:
  indent:
    - error
    - 2
  object-curly-spacing:
    - error
    - always

  solid/no-unknown-namespaces: 0
  solid/no-react-specific-props: error

  "@typescript-eslint/strict-boolean-expressions": 0
  "@typescript-eslint/consistent-type-assertions": 0
  "@typescript-eslint/consistent-type-definitions": 0
  "@typescript-eslint/consistent-indexed-object-style": 0
